CHANGELOG for entities
tesla-local-control/tesla_ble_mqtt_core pull request #65
Opened 2024-07-08 23:36 UTC by baylanger

2024-07-09 14:50 UTC, raphmur approved these changes

2024-07-09 14:51 UTC, raphmur requested changes

2024-07-09 14:51 UTC, raphmur commented on CHANGELOG.md
> +- CHG: Renamew entities for consistency & better wording
oops typo there

2024-07-09 22:29 UTC, raphmur approved these changes

2024-07-10 04:17 UTC, iainbullock approved these changes

2024-07-10 04:18 UTC, merged